</h3><b>Add New product</b></h3>
<div class="form656">

    <form action=”<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>” method="post">
   <label> Product Name</label><br/> <input name="pname" type="text"/><br/>
   <label>price</</label><br/><input name="price" type="text"/><br/>
   <select name="category">
        <option value="Veg">Veg</option>
        <option value="NonVeg">NonVeg</option>
    </select><br/>
  <label> Description</label><br/> <input name="description" type="text"/><br/>
    <label>image</label> <br/><input type="file" name="pic" accept="image/*"/><br/>
<br/>

<input type="submit" name="submit" value="save product"/>

</form>

</div>
