<?php
/* @var \Codilaar\HelloWorld\Block\HelloWorld $block */
?>
<div class="block block-dashboard-info">
<h3><b>Add New product</b></h3>
<div class="form656">

    <form action="<?= $block->getUrl("hello/index/productPost") ?>" method="post">
        <label> Product Name</label><br/> <input name="pname" type="text"/><br/>
        <label>price</</label><br/><input name="price" type="text"/><br/>
        <label>description</</label><br/><input name="description" type="text" /><br/>
        <select name="category">
            <?php foreach ($block->getAllCategories() as $category): ?>
                <?php /* @var \Magento\Catalog\Model\Category $category */ ?>
                <option value="<?= $category->getId() ?>"><?= $category->getName() ?></option>
            <?php endforeach; ?>
        </select><br/>
        <label>image</label> <br/><input type="file" name="pic" accept="image/*"/><br/>
        <br/>

        <input type="submit" name="submit" value="save product"/>

    </form>

</div>
</div>